index:
    path: /
    controller: App\Controller\HomeController::index
article:
    path: /article
    controller: App\Controller\ArticleController::article

propos:
    path: /propos
    controller: App\Controller\ProposController::propos

contact:
    path: /contact
    controller: App\Controller\ContactController::contact
connexion:
    path: /connexion
    controller: App\Controller\SecurityController::login